/* ************************************************************************** */
/*                                                                            */
/*                                                        :::      ::::::::   */
/*   ms_structs.h                                       :+:      :+:    :+:   */
/*                                                    +:+ +:+         +:+     */
/*   By: fpaglia <fpaglia@student.42vienna.com>     +#+  +:+       +#+        */
/*                                                +#+#+#+#+#+   +#+           */
/*   Created: 2025/10/01 09:13:51 by fpaglia           #+#    #+#             */
/*   Updated: 2025/10/13 15:45:14 by fpaglia          ###   ########.fr       */
/*                                                                            */
/* ************************************************************************** */

#ifndef MS_STRUCTS_H
# define MS_STRUCTS_H

# include <sys/types.h>

/* This stucture represents the way the current program relates to the 
 * surrounding ones.
 * - pipe: has at least a process that follows.
 * - end: last item of the process
 */
typedef enum e_pipe
{
	ispipe,
	end
}	t_pipe;

/* This structure represents the core items required to execute a program:
 * - id:		current program id (from the list that needs execution).
 * - cpid:		child process hosting the program execution.
 * - go_to:		how the current program connects with its surrounding.
 * - f_stdin:	file that has to be used to redirect stdin.
 *   			If the string is prefixed with < then it's an here_doc.
 * - f_stdout:	file that has to be used to redirect stdout.
 *   			If the string is prefixed with > then append to the end of 
 *   			current content.
 * - fd_io:		pair of fd generated by the pipe to comunicate between
 *   			subprocesses.
 * - prog:		array of commands and parameter to pass to execve.
 * - complete:	exit value of the given subprocess.
 */
typedef struct s_prog
{
	int		id;
	int		cpid;
	t_pipe	go_to;
	char	*f_stdin;
	char	*f_stdout;
	int		fd_io[2];
	char	**prog;
	int		complete;
}	t_prog;

/* This structure provides flexible metadata to extend an array.
 * arr:			the current character array
 * size:		current amount of used pointers;
 * capacity:	maximum amount of pointers that can be stored 
 * 				before the array has to be expanded;
 */
typedef struct s_arr
{
	char	**arr;
	ssize_t	size;
	ssize_t	capacity;
}			t_arr;

/* This structure represents the entry point to process the shell inputs:
 * cmd_str:		raw string received as input;
 * count:		amount of program found in the str.
 * items:		structure of the program to be executed.
 * sys_env:		system wide environment variables.
 * env_path:	paths defined in the environment are here presented in an 
 * 				iterable array.
 */
typedef struct s_shell
{
	char	*cmd_line;
	int		count;
	t_prog	*items;
	t_arr	*env;
}	t_shell;

#endif
